image: docker:19.03.1

variables:
  DOCKER_TLS_CERTDIR: "/certs"
  CONTAINER_NAME: "dev1"
  DOCKER_USER: "viethddoc"
  DOCKER_PASSWORD: "123@123a123A"
  IMAGE_VER: "1.0.2"

#   DOCKER_HOST: tcp://172.18.10.158:2376

services:
  - docker:19.03.1-dind

stages:
  # - unitest
  # - featuretest
  - commit
  - deployproduct_stage

# before_script:
#    # - docker login -u viethdoc -p 123@123a123A
#    - whoami

# unitest:
#   tags:
#     - docker
#   stage: unitest
#   image: php:7.0
#   script:
#     # - echo $TEST
#     - ls
#     - apt-get update -yqq >/dev/null 2>&1
#     - apt-get install git -yqq >/dev/null 2>&1
#     - curl --location --output /usr/local/bin/phpunit https://phar.phpunit.de/phpunit-6.5.9.phar >/dev/null 2>&1
#     - chmod +x /usr/local/bin/phpunit
#     - phpunit --bootstrap autoload.php EmailTest
#   when: always

# featuretest:
#   tags:
#     - sock
#   stage: featuretest
#   script:
#     - docker rename $(docker create -p 9005:80/tcp richarvey/nginx-php-fpm) $CONTAINER_NAME; docker start $CONTAINER_NAME
#     - docker cp Email.php $CONTAINER_NAME:/var/www/html/index.php
#     - echo "Website http://172.18.10.158:9005"
#     - echo "Done1"
#   when: always

commit:
  tags:
    - sock
  stage: commit
  script:
    - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - docker commit $CONTAINER_NAME viethddoc/test:$IMAGE_VER
    - docker push viethddoc/test:$IMAGE_VER >/dev/null 2>&1
    - docker commit $CONTAINER_NAME viethddoc/test:lastest
    - docker push viethddoc/test:lastest >/dev/null 2>&1
    - docker logout
    ####
    - docker stop $CONTAINER_NAME
    - docker rm $CONTAINER_NAME
  # when: manual
  when: always

deployproduct_stage:
  tags:
    - shell
  stage: deployproduct_stage
  script:
    - docker ps
    - if [[ $(docker ps -q -f ancestor=viethddoc/test:lastest) ]]; then docker stop $(docker ps -q -f ancestor=viethddoc/test:lastest); fi
    - docker pull viethddoc/test:lastest
    # - docker ps -q -f ancestor=richarvey/nginx-php-fpm
    - docker run -d -p 80:80  viethddoc/test:lastest
  # when: manual
  when: always



